package constants

const (
	SEAT_CATEGORY_SILVER = iota + 1
	SEAT_CATEGORY_GOLD
	SEAT_CATEGORY_PLATINUM
)

const (
	SEAT_STATUS_AVAILABLE = iota + 1
	SEAT_STATUS_BOOKED
)

const (
	BOOKING_STATUS_CONFIRMED = iota + 1
	BOOKING_STATUS_PENDING
	BOOKING_STATUS_FAILED
)
