package constants

const (
	RATE_LIMITER_TOKEN_BUCKET = iota + 1
	RATE_LIMITER_LEAKY_BUCKET
	RATE_LIMITER_FIXED_WINDOW_COUNTER
	RATE_LIMITER_SLIDING_WINDOW_LOG
	RATE_LIMITER_SLIDING_WINDOW_COUNTER
)

const (
	API_GET_CART = iota + 1
)
